export const projects = [
  {
    title: "E-Commerce Platform",
    description: "Platform e-commerce fullstack...",
    category: "website",
    tech: ["Laravel", "Vue.js", "MySQL"],
    slug: "ecommerce-platform",
    image: "/images/copy.png",
  },
  {
    title: "E-Commerce Platform",
    description: "Platform e-commerce fullstack...",
    category: "website",
    tech: ["Laravel", "Vue.js", "MySQL"],
    slug: "ecommerce-platform",
    image: "/images/copy.png",
  },
  {
    title: "E-Commerce Platform",
    description: "Platform e-commerce fullstack...",
    category: "website",
    tech: ["Laravel", "Vue.js", "MySQL"],
    slug: "ecommerce-platform",
    image: "/images/copy.png",
  },
    {
    title: "E-Commerce Platform",
    description: "Platform e-commerce fullstack...",
    category: "website",
    tech: ["Laravel", "Vue.js", "MySQL"],
    slug: "ecommerce-platform",
    image: "/images/copy.png",
  },
  {
    title: "E-Commerce Platform",
    description: "Platform e-commerce fullstack...",
    category: "website",
    tech: ["Laravel", "Vue.js", "MySQL"],
    slug: "ecommerce-platform",
    image: "/images/copy.png",
  },
  {
    title: "E-Commerce Platform",
    description: "Platform e-commerce fullstack...",
    category: "mobile",
    tech: ["Laravel", "Vue.js", "MySQL"],
    slug: "ecommerce-platform",
    image: "/images/copy.png",
  },
    {
    title: "E-Commerce Platform",
    description: "Platform e-commerce fullstack...",
    category: "mobile",
    tech: ["Laravel", "Vue.js", "MySQL"],
    slug: "ecommerce-platform",
    image: "/images/copy.png",
  },
  {
    title: "E-Commerce Platform",
    description: "Platform e-commerce fullstack...",
    category: "website",
    tech: ["Laravel", "Vue.js", "MySQL"],
    slug: "ecommerce-platform",
    image: "/images/copy.png",
  },
  {
    title: "E-Commerce Platform",
    description: "Platform e-commerce fullstack...",
    category: "arvr",
    tech: ["Laravel", "Vue.js", "MySQL"],
    slug: "ecommerce-platform",
    image: "/images/copy.png",
  },
  {
    title: "E-Commerce Platform",
    description: "Platform e-commerce fullstack...",
    category: "website",
    tech: ["Laravel", "Vue.js", "MySQL"],
    slug: "ecommerce-platform",
    image: "/images/copy.png",
  },
  {
    title: "E-Commerce Platform",
    description: "Platform e-commerce fullstack...",
    category: "mobile",
    tech: ["Laravel", "Vue.js", "MySQL"],
    slug: "ecommerce-platform",
    image: "/images/copy.png",
  },
    {
    title: "E-Commerce Platform",
    description: "Platform e-commerce fullstack...",
    category: "mobile",
    tech: ["Laravel", "Vue.js", "MySQL"],
    slug: "ecommerce-platform",
    image: "/images/copy.png",
  },
  {
    title: "E-Commerce Platform",
    description: "Platform e-commerce fullstack...",
    category: "website",
    tech: ["Laravel", "Vue.js", "MySQL"],
    slug: "ecommerce-platform",
    image: "/images/copy.png",
  },
  {
    title: "E-Commerce Platform",
    description: "Platform e-commerce fullstack...",
    category: "arvr",
    tech: ["Laravel", "Vue.js", "MySQL"],
    slug: "ecommerce-platform",
    image: "/images/copy.png",
  },
];